# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a9454978da182f493063c05c71f3aae6dfb7e219ff56c0e37c25553f1ca8f01fdcb342874257d5997ef7b0b5765fdf10d0e18a8ab5a9dffeee20e9f203df375

test:
  secret_key_base: eb4fbc5a5e315514066661564f4d0e3f25656669bd1155bd8d4066e9fc412f2ea91400b2e29f4eeff6c3384b40b62a98c1cfcef2b609a5422539374453086f92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
